version: '3.8'

services:
  backend:
    image: vvduth/dukem-learning-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dukem-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - dukem-network

  frontend:
    image: vvduth/dukem-learning-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dukem-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - dukem-network

networks:
  dukem-network:
    driver: bridge